export const authConstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"FAILURE",
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    FORGET_PASS:"FORGET_PASS",
    FORGET_SUCC:"FORGET_SUCC",
    POSTJOB_REQUEST:"POSTJOB_REQUEST",
    POSTJOB_SUCCESS:"POSTJOB_SUCCESS",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    UPDATE_REQUEST:"UPDATE_REQUEST",
    UPDATE_SUCCESS:"UPDATE_SUCCESS",
    RESUME_REQUEST:"RESUME_REQUEST",
    RESUME_SUCCESS:"RESUME_SUCCESS",
    EXISTED_RECRUTER:"EXISTED_RECRUTER",
    ADD_FAVOURITEL:"ADD_FAVOURITE",
    GET_FAVOURITE:"GET_FAVOURITE",
    DELETE_FAVORITE:"DELETE_FAVORITE"

}